name: License Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: license check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: LicenseCheck
        run: python3 ./scripts/license_check.py
